<img src="img/LP_V1_M3.png"/>

<div class="alert alert-block alert-info">
<b><span style="font-family:Comic Sans MS">Linear Optimization: A maximization example with linear programming</span></b>
</div>

In [ ]:
# !pip install pulp

In [1]:
#Diable the warnings
import warnings
warnings.filterwarnings('ignore')

In [2]:
""" 
A linear optimization problem with 2 variables
"""
import pulp

x = pulp.LpVariable('x', lowBound=0)
y = pulp.LpVariable('y', lowBound=0)

problem = pulp.LpProblem(
    'A simple maximization objective', 
    pulp.LpMaximize)
problem += 5*x + 3*y, 'The objective function'
problem += 2*x + y <= 100, '1st constraint'
problem += x + y <= 90, '2nd constraint'
problem += x <= 55, '3rd constraint'
problem.solve()

1

In [3]:
print("Maximization Results:")
for variable in problem.variables():
    print(variable.name, '=', variable.varValue)

Maximization Results:
x = 10.0
y = 80.0


<div class="alert alert-block alert-info">
<b><span style="font-family:Comic Sans MS">Linear Optimization: A minimization example with integer programming</span></b>
</div>

In [4]:
""" 
An example of implementing an integer 
programming model with binary conditions 
"""
import pulp

dealers = ['X', 'Y', 'Z']
variable_costs = {'X': 470, 'Y': 346, 'Z': 450}
fixed_costs = {'X': 3300, 'Y': 5900, 'Z': 6865}

# Define PuLP variables to solve
quantities = pulp.LpVariable.dicts('quantity', 
                                   dealers, 
                                   lowBound=0,
                                   cat=pulp.LpInteger)
is_orders = pulp.LpVariable.dicts('orders', 
                                  dealers,
                                  cat=pulp.LpBinary)

In [5]:
"""
This is an example of implementing an 
IP model with binary variables the correct way.
"""
# Initialize the model with constraints
model = pulp.LpProblem('A cost minimization problem',
                       pulp.LpMinimize)
model += sum(
    [variable_costs[i]*quantities[i] + \
         fixed_costs[i]*is_orders[i] for i in dealers])\
    , 'Minimize portfolio cost'
model += sum([quantities[i] for i in dealers]) == 175\
    ,  'Total contracts required'
model += is_orders['X']*35 <= quantities['X'] <= \
    is_orders['X']*100, 'Boundary of total volume of X'
model += is_orders['Y']*35 <= quantities['Y'] <= \
    is_orders['Y']*90, 'Boundary of total volume of Y'
model += is_orders['Z']*35 <= quantities['Z'] <= \
    is_orders['Z']*70, 'Boundary of total volume of Z'
model.solve()

1

In [6]:
print('Minimization Results:')
for variable in model.variables():
    print(variable, '=', variable.varValue)

print('Total cost:',  pulp.value(model.objective))

Minimization Results:
orders_X = 1.0
orders_Y = 1.0
orders_Z = 0.0
quantity_X = 85.0
quantity_Y = 90.0
quantity_Z = 0.0
Total cost: 80290.0


<div class="alert alert-block alert-info">
<b><span style="font-family:Comic Sans MS">Solving linear equations using matrices </span></b>
</div>

In [7]:
""" 
Linear algebra with NumPy matrices 
"""
import numpy as np

A = np.array([[22, 11, 11],[11, 31, 21],[11, 1, 1]])
B = np.array([40, 50, 60])

In [8]:
print(np.linalg.solve(A, B))

[  6.26262626  16.77777778 -25.66666667]


<div class="alert alert-block alert-info">
<b><span style="font-family:Comic Sans MS">The LU decomposition </span></b>
</div>

In [9]:
""" 
LU decomposition with SciPy 
"""
import numpy as np
import scipy.linalg as linalg


# Define A and B
A = np.array([
    [20., 11., 14.],
    [14., 35., 27.],
    [11., 9., 11.]])
B = np.array([40., 50., 60.])

# Perform LU decompositiopn
LU = linalg.lu_factor(A)
x = linalg.lu_solve(LU, B)

In [10]:
print(x)

[ -7.17916137 -14.76493011  24.71410419]


In [11]:
import scipy

P, L, U = scipy.linalg.lu(A)

print('P=\n', P)
print('L=\n', L)
print('U=\n', U)

P=
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
L=
 [[1.         0.         0.        ]
 [0.7        1.         0.        ]
 [0.55       0.10805861 1.        ]]
U=
 [[20.         11.         14.        ]
 [ 0.         27.3        17.2       ]
 [ 0.          0.          1.44139194]]


<div class="alert alert-block alert-info">
<b><span style="font-family:Comic Sans MS">The Cholesky decomposition </span></b>
</div>

In [12]:
""" 
Cholesky decomposition with NumPy 
"""
import numpy as np

A = np.array([
    [10., -1., 2., 0.],
    [-1., 11., -1., 3.],
    [2., -1., 11., -1.],
    [0., 3., -1., 81.]])
B = np.array([6., 25., -11., 15.])

L = np.linalg.cholesky(A)

In [13]:
print(L)

[[ 3.16227766  0.          0.          0.        ]
 [-0.31622777  3.3015148   0.          0.        ]
 [ 0.63245553 -0.24231301  3.24673442  0.        ]
 [ 0.          0.9086738  -0.24018488  8.95078897]]


In [14]:
print(np.dot(L, L.T.conj()))  # A=L.L*

[[10. -1.  2.  0.]
 [-1. 11. -1.  3.]
 [ 2. -1. 11. -1.]
 [ 0.  3. -1. 81.]]


In [15]:
y = np.linalg.solve(L, B)  # L.L*.x=B; When L*.x=y, then L.y=B

In [16]:
x = np.linalg.solve(L.T.conj(), y)  # x=L*'.y

In [17]:
print(x)

[ 1.01974928  2.25254742 -0.97247268  0.08975167]


In [18]:
print(np.mat(A) * np.mat(x).T)  # B=Ax

[[  6.]
 [ 25.]
 [-11.]
 [ 15.]]


<div class="alert alert-block alert-info">
<b><span style="font-family:Comic Sans MS">Solving with linear/Matrix Algebra </span></b>
</div>

__Jacobi Method__

In [19]:
"""
Solve Ax=B with the Jacobi method 
"""
import numpy as np

def jacobi(A, B, n, tol=1e-10):
    # Initializes x with zeroes with same shape and type as B
    x = np.zeros_like(B)

    for iter_count in range(n):
        x_new = np.zeros_like(x)
        for i in range(A.shape[0]):
            s1 = np.dot(A[i, :i], x[:i])
            s2 = np.dot(A[i, i + 1:], x[i + 1:])
            x_new[i] = (B[i] - s1 - s2) / A[i, i]

        if np.allclose(x, x_new, tol):
            break

        x = x_new

    return x

In [20]:
A = np.array([
    [15., -1., 2., 0.], 
    [-1., 11., -1., 3.], 
    [2., -1., 100., -1.], 
    [0.0, 3., -1., 8.]])
B = np.array([6., 25., -11., 15.])
n = 25

In [21]:
x = jacobi(A, B, n)
print('x', '=', x)

x = [ 0.54607116  2.01164576 -0.08971078  1.10941899]


__The Gauss-Seidel method__

In [22]:
""" 
Solve Ax=B with the Gauss-Seidel method 
"""
import numpy as np


def gauss(A, B, n, tol=1e-10):
    L = np.tril(A)  # returns the lower triangular matrix of A
    U = A-L  # decompose A = L + U
    L_inv = np.linalg.inv(L)
    x = np.zeros_like(B)

    for i in range(n):
        Ux = np.dot(U, x)
        x_new = np.dot(L_inv, B - Ux)

        if np.allclose(x, x_new, tol):
            break

        x = x_new

    return x

In [23]:
A = np.array([
    [115., -1., 2., 0.], 
    [-1., 11., -1., 3.], 
    [2., -1., 110., -1.], 
    [0.0, 3., -1., 8.]])
B = np.array([6., 25., -11., 15.])
n = 2500

In [24]:
print('x', '=', x)

x = [ 0.54607116  2.01164576 -0.08971078  1.10941899]
